# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          registry_username: ${{secrets.USR}}
          registry_password: ${{secrets.PWD }}
#  docker:
##    uses: ./.github/workflows/w1.yml
##    with:
#      image_name: my-awesome-app
#      tag: $GITHUB_RUN_NUMBER
#    secrets:
#      registry_username: ${{secrets.USR}}
#      registry_password: ${{secrets.PWD}}
